### PR TITLE
Create a sandbox ns & enforce rbac for gitlab-runner

### PR DESCRIPTION
**Pull request by Michael-Kruggel**
- Made a sandbox namespace for the gitlab-runner job pods to use that isn't restricted by zarf
- Added some RBAC to gitlab-runner to restrict some of its capabilities

### CODE REVIEW

**Review by corang — APPROVED** [review]

**Review by anthonywendt — APPROVED** [review]

**Comment by bburky** [comment]
A ClusterRole with permissions on Pods and Secrets is still extremely permissive. What is the intent of this sandbox?

**Pull request merged**
