### PR TITLE
Change checklist into table

### PR DESCRIPTION
**Pull request by jacobbmay**
PR for issue #20

### CODE REVIEW

**Comment by anthonywendt** [comment]
Updated to use new vocabulary used from [this](https://github.com/defenseunicorns/uds/blob/main/docs/adr/0010-uds-bundle-definition-with-release-life-cycle.md) adr

**Comment by jacobbmay** [comment]
Should mattermost even be in this table? Wouldn't it be apart of the separate collab package instead of actually being apart of the SWF?

**Comment by anthonywendt** [comment]
> Should mattermost even be in this table? Wouldn't it be apart of the separate collab package instead of actually being apart of the SWF?

Thats a great question. We are actively trying to figure out exactly what this project is and should contain. We could for now just have the table include gitlab, gitlab-runner and sonarqube. Maybe just make the next entry be TBD.

**Comment by corang** [comment]
Implemented in #96

**Pull request closed without merging**
