### PR TITLE
Initial contributors guide

### PR DESCRIPTION
**Pull request by mikevanhemert**
I used inspiration from Zarf and the internet to create this initial Contributors guide.

### CODE REVIEW

**Review by RothAndrew — APPROVED** [review]
❤️

**Comment by oates** [comment]
🙌🏼

**Review by anthonywendt — DISMISSED** [review]
LGTM

**Review by Michael-Kruggel — APPROVED** [review]

**Comment by zachariahmiller** [comment]
@mikevanhemert This is great and its good to have a contributing guide at the repo level, but i think we need to apply this across all UDS packages and capabilities. I have made a [wiki page](https://github.com/defenseunicorns/uds/wiki/UDS-Packages-Capabilities-Common-Definition-of-Done) as an interim solution to link to in the DoD section across all tickets coming down the pipe, with the intent that it will all be captured as a UDS level ADR, which can be referenced in the future.

**Comment by anthonywendt** [comment]
> 

So is it okay to merge this in as is? Do we need to link to that wiki and add a note about a WIP ADR related to definition of done? @zachariahmiller @mikevanhemert

**Review by anthonywendt — APPROVED** [review]

**Comment by zachariahmiller** [comment]
> > @mikevanhemert This is great and its good to have a contributing guide at the repo level, but i think we need to apply this across all UDS packages and capabilities. I have made a [wiki page](https://github.com/defenseunicorns/uds/wiki/UDS-Packages-Capabilities-Common-Definition-of-Done) as an interim solution to link to in the DoD section across all tickets coming down the pipe, with the intent that it will all be captured as a UDS level ADR, which can be referenced in the future.
> 
> So is it okay to merge this in as is? Do we need to link to that wiki and add a note about a WIP ADR related to definition of done? @zachariahmiller @mikevanhemert

I dont feel strongly either way about the path forward. I had made that wiki page to reference in the issues as i was trying to organize them. I dont think that or the potential ADR should be a reason to not merge this PR.

**Pull request merged**
