### PR TITLE
ADR for the mechanism for running tests

### PR DESCRIPTION
**Pull request by RothAndrew**
Create the ADR for how we intend for tests to be run, both locally and in CI.

This first draft is intended to stimulate discussion and debate, in the hopes that we come to a solution that the team likes and enjoys working with.

### CODE REVIEW

**Comment by anthonywendt** [comment]
I can't argue with anything here. We did take a stab in the gilab capability with using the github action that dubbd uses to spin up a test k3d cluster for use. https://github.com/defenseunicorns/uds-capability-gitlab/blob/main/.github/workflows/build-test.yml. That seems to work pretty well.

But I understand the desire to have the tests be the same for local and ci. 

How do we address testing across the other k8s distros and environments?

**Comment by RothAndrew** [comment]
> How do we address testing across the other k8s distros and environments?
TBD. The existing pattern is Terratest, which I'm still a fan of.

**Review by zachariahmiller — COMMENTED** [review]
An additional consequence of the decisions you wrote up is that ~90% (or something) of the CI is portable across SCM+CI/CD tools. In other words with the approach you defined, with minimal glue the processes could "just work" with github and gitlab.

**Review by anthonywendt — APPROVED** [review]
LGTM

**Comment by RothAndrew** [comment]
Waiting to merge until more people see this and have a chance to respond to it.

**Comment by mikevanhemert** [comment]
@RothAndrew have you compared the proposed solutions here to what is being used across the rest of the UDS effort? While we might not use the same shared workflows off-the-bat, the solutions will eventually converge.

**Comment by RothAndrew** [comment]
> @RothAndrew have you compared the proposed solutions here to what is being used across the rest of the UDS effort? While we might not use the same shared workflows off-the-bat, the solutions will eventually converge.

Yes

**Review by Michael-Kruggel — APPROVED** [review]
LGTM

**Review by corang — APPROVED** [review]
I don't have any issues with this

**Comment by RothAndrew** [comment]
Based on the conversation we had I'm going to go create the PR for this in the UDS repo (will try and figure out some way of designating that it is a SWF-specific decision), then I'll close this PR.

**Comment by RothAndrew** [comment]
OBE. Replaced by https://github.com/defenseunicorns/uds/pull/170

**Pull request closed without merging**
