### PR TITLE
Add m1 mac support to makefile

### PR DESCRIPTION
**Pull request by zachariahmiller**

### CODE REVIEW

**Review by anthonywendt — APPROVED** [review]
LGTM

**Review by mikevanhemert — DISMISSED** [review]

**Review by Michael-Kruggel — APPROVED** [review]
Looks good to me

**Comment by zachariahmiller** [comment]
i had to make another tiny change for zarf init command to "just work". Assuming the test passes here, which it should, i'll go through and update the other capability Makefile's to be in line with these changes.

**Review by anthonywendt — APPROVED** [review]

**Pull request merged**
